### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by kmmbvnr** [thomlinton/django-trackable#1]
Celery could run the new task when the previous still works.

And you have update fields with get/+=/save workflow that doesn't safe. (http://stackoverflow.com/questions/1030270/race-conditions-in-django)

It is better to use F objects for operations. See - http://docs.djangoproject.com/en/1.1/ref/models/instances/#updating-attributes-based-on-existing-fields

**Comment by thomlinton** [comment]
I was aware that the hot spots weren't necessarily free from race conditions; however, it was produced out of a need in an environment that has per-view transactions and ran celery with CELERYD_CONCURRENCY=1. I neglected to make a note of these points and thank you for the reminder.

I've got some changes that should resolve race conditions in a more black-box manner.

Thank you as well for the suggestion to use F expressions, as I'd agree it'd bring a bit more clarity to the implementation.
